services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: laravel_app
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel_app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
networks:
  laravel_app:
    driver: bridge
